/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package primericon;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author aguilera
 */
public class principal extends javax.swing.JFrame {

    private int i=0;
    private String[] imagenes={"/imagenes/java_net.jpeg","/imagenes/codigo.jpeg","/imagenes/java.png"};
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDeportes = new javax.swing.ButtonGroup();
        buttonGroupCurso = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabelImagenes = new javax.swing.JLabel();
        jButtonCambiar = new javax.swing.JButton();
        jRadioButtonTenis = new javax.swing.JRadioButton();
        jRadioButtonPingpong = new javax.swing.JRadioButton();
        jRadioButtonBasket = new javax.swing.JRadioButton();
        jRadioButton1dam = new javax.swing.JRadioButton();
        jRadioButton2dam = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setMnemonic('I');
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Imagen SI/NO");
        jCheckBox1.setActionCommand("");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jLabelImagenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/java_net.jpeg"))); // NOI18N

        jButtonCambiar.setText("NEXT IMAGE");
        jButtonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarActionPerformed(evt);
            }
        });

        buttonGroupDeportes.add(jRadioButtonTenis);
        jRadioButtonTenis.setText("Tenis");

        buttonGroupDeportes.add(jRadioButtonPingpong);
        jRadioButtonPingpong.setText("Ping pong");

        buttonGroupDeportes.add(jRadioButtonBasket);
        jRadioButtonBasket.setText("Basket");

        buttonGroupCurso.add(jRadioButton1dam);
        jRadioButton1dam.setText("1º DAM");

        buttonGroupCurso.add(jRadioButton2dam);
        jRadioButton2dam.setText("2º DAM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonCambiar)
                                .addComponent(jRadioButtonTenis))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jRadioButtonPingpong)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jRadioButtonBasket)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1dam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton2dam, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1dam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2dam)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonCambiar)
                        .addGap(54, 54, 54)
                        .addComponent(jRadioButtonTenis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPingpong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonBasket)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ponerImagen(){
        ImageIcon ii=new ImageIcon(getClass().getResource(imagenes[i]));  

        Image image= ii.getImage().getScaledInstance(200, 200, Image.SCALE_REPLICATE);
        jLabelImagenes.setIcon(new ImageIcon(image));  
//        jLabelImagenes.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagenes[i])));  
    }
    
    private void jButtonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarActionPerformed
        i++;
        i=i%3;
        ponerImagen();
    }//GEN-LAST:event_jButtonCambiarActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        if (jCheckBox1.isSelected())
            ponerImagen();
        else
        {
            jLabelImagenes.setIcon(null);
            jLabelImagenes.setText("SIN IMAGEN");
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCurso;
    private javax.swing.ButtonGroup buttonGroupDeportes;
    private javax.swing.JButton jButtonCambiar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabelImagenes;
    private javax.swing.JRadioButton jRadioButton1dam;
    private javax.swing.JRadioButton jRadioButton2dam;
    private javax.swing.JRadioButton jRadioButtonBasket;
    private javax.swing.JRadioButton jRadioButtonPingpong;
    private javax.swing.JRadioButton jRadioButtonTenis;
    // End of variables declaration//GEN-END:variables
}
